server:
  port: 8080
spring:
  datasource:
    druid:
      name: filebed
      url: jdbc:oracle:thin:@127.0.0.1:1521/xe
      username: C##FILEBED
      password: root
      testWhileIdle: true
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl