spring:
  application:
    name: Drawing bed
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  servlet:
    context-path: /
mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
  configuration:
    # 驼峰
    map-underscore-to-camel-case: false

file:
  save-path: D:/file/
  temp-path: D:/file/temp/