server:
  port: 8080
spring:
  datasource:
    druid:
      name: mariadb-01
      url: jdbc:mariadb://localhost:3306/drawing_bed
      username: root
      password: root
      testWhileIdle: true
      validationQuery: SELECT 1