server:
  port: 8080
spring:
  datasource:
    druid:
      name: filebed
      url: jdbc:mariadb://localhost:3306/filebed
      username: root
      password: root
      testWhileIdle: true
      validationQuery: SELECT 1
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl